repos:

-   repo: https://github.com/ikamensh/flynt
    rev: ''  # Specify a specific version if desired
    hooks:
    -   id: flynt
        args: [ "--line-length", "160"]  # Flynt does not support pyproject.toml in special locations

-   repo: https://github.com/psf/black
    rev: 23.9.1
    hooks:
    -   id: black
        types: [python]
        args: ["--config", "pyproject.toml"]

-   repo: https://github.com/pycqa/isort
    rev: 5.12.0
    hooks:
    -   id: isort
        name: isort (python)
        args: ["--settings-path", "pyproject.toml"]
